# -*- coding: utf-8 -*-
"""v2-06-Abr-L1-L2-Optimization-Pos-Deep-Learning-Projeto-NLP-Sentinel-Projeto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EM1U2WL0-wAQAfBnVyICqpG7qOdmVYD3

# 🛡️ NLP-Sentinel

## Análise de Sentimento em Avaliações de Produtos

- #### Curso: Pós-Graduação em Deep Learning (CIn - UFPE)  
- ##### Disciplina: Projeto em Deep Learning  
  - ##### Professor: Cléber Zanchettin  

- ##### Aluno:  
  - Luciano Ayres Farias de Carvalho (lafc@cin.ufpe.br)

---

## 📖 Sobre o Projeto

### 🔍 Visão Geral  
O **NLP-Sentinel** é um projeto de **Processamento de Linguagem Natural (PLN)** focado na análise de sentimentos em avaliações de produtos, utilizando **modelos de linguagem pré-treinados (LLMs)** e técnicas modernas de **representação vetorial de sentenças** para gerar resultados eficientes sem depender de redes profundas treinadas do zero.

---

## 🎯 Objetivos
- Classificar avaliações de consumidores como **positivas**, **neutras** ou **negativas** com base no conteúdo textual.
- **Correlacionar sentimentos** com as notas (de 1 a 5 estrelas) atribuídas pelos clientes.
- **Explorar padrões linguísticos** nas avaliações, identificando tópicos recorrentes em diferentes polaridades.
- Comparar o desempenho de **modelos sem necessidade de fine-tuning** com abordagens mais tradicionais.

---

## 🤖 Modelos e Técnicas Utilizadas

### 🧠 Representação Vetorial + Classificação:
- 🔹 **SVM + Universal Sentence Encoder (USE)**  
  Abordagem leve e eficaz que combina embeddings semânticos do USE com um classificador SVM tradicional, gerando bons resultados com baixo custo computacional.

### 🚀 Modelos Pré-treinados:
- 🔹 **BERT**, **DistilBERT**, **XLM-Roberta** (via Hugging Face Transformers)
- 🔹 **Sentence-Transformers** para extração de embeddings de alta qualidade

### 🧪 IA Generativa (LLMs):
- 🔹 **In-Context Learning** com **OpenAI GPT**
- 🔹 **In-Content Learning** com **Google Gemini**

> Técnicas como SVM com Bag of Words/Embeddings e redes neurais LSTM/RNN foram descontinuadas nesta versão por apresentarem menor desempenho e alto custo de execução.

---

## 📊 Base de Dados

O projeto utiliza o dataset [Olist Store](https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce/data), um conjunto público de e-commerce brasileiro contendo mais de 100 mil pedidos feitos entre 2016 e 2018.

- **Texto dos Comentários**: avaliações textuais feitas por consumidores
- **Review Score**: notas de 1 a 5 atribuídas aos produtos

> Os dados foram anonimizados e editados com nomes fictícios (como casas de *Game of Thrones*) para garantir privacidade e permitir abordagens criativas.

---

## 🧠 Diferenciais do Projeto

- Foco em **simplicidade, desempenho e baixo custo computacional**
- Uso de **LLMs e embeddings semânticos** com alto poder de generalização
- Integração com **IA generativa** sem necessidade de treinamento adicional
- Visualizações com **nuvens de palavras**, **matrizes de confusão** e **métricas** claras

---

## 💡 Por que o nome *NLP-Sentinel*?

Porque o sistema atua como um **sentinela inteligente**, sempre atento às emoções, opiniões e padrões revelados pelos consumidores – extraindo insights diretamente da linguagem natural.

# Resumo dos Resultados

O projeto **NLP-Sentinel** investigou diferentes abordagens para classificar sentimentos (positivo ou negativo) em avaliações reais de produtos da Olist, usando modelos de aprendizado supervisionado, embeddings semânticos e LLMs (Large Language Models).

---

#### ✅ Desempenho dos Modelos Supervisionados

| Modelo                    | Acurácia (%) | F1-Score (%) |
|---------------------------|--------------|--------------|
| **BERT**                  | **94.26**    | **94.37**    |
| **RoBERTa**               | 93.83        | 93.94        |
| **DistilBERT**            | 93.23        | 93.37        |
| **SVM + Sentence-BERT**   | 92.88        | 93.01        |
| **SVM + USE**             | 92.59        | 92.72        |

---

#### 🤖 Desempenho de LLMs (Zero-shot)

| Modelo               | Acurácia (%) | Acertos | Erros |
|----------------------|--------------|---------|-------|
| **OpenAI GPT-4**     | **100.0**    | 10      | 0     |
| **Google Gemini 1.5**| 90.0         | 9       | 1     |

> 🔎 **Destaque:** O modelo **BERT** fine-tunado teve o melhor desempenho entre os supervisionados. O **GPT-4** obteve **100% de acurácia** mesmo sem treinamento, mostrando a força dos modelos generativos modernos com *In-Context Learning*.

---

### ✅ **Conclusão**

O projeto **NLP-Sentinel** demonstrou que é possível alcançar alta precisão na análise de sentimentos em português por meio de diferentes estratégias. A experimentação com modelos supervisionados, embeddings e LLMs proporcionou insights valiosos sobre desempenho, custo e aplicabilidade em cenários reais.

---

#### 🧠 Principais Aprendizados

- 💡 **Modelos híbridos**, como **Sentence-BERT combinado com SVM**, mostraram-se bastante competitivos, entregando bons resultados com baixo consumo de recursos — ideais para aplicações com restrições computacionais.

- 🚀 **Modelos generativos como GPT-4 e Gemini** demonstraram excelente desempenho **sem necessidade de treinamento adicional**, revelando-se altamente eficazes para tarefas pontuais e protótipos rápidos com *zero-shot learning*.

- ⚖️ **Simplicidade e eficiência importam**: Técnicas como **SVM com Bag of Words/Embeddings** e **redes neurais LSTM/RNN** foram **abandonadas** nesta versão do projeto por apresentarem **baixo desempenho e alto custo de execução**, reforçando a importância da análise criteriosa de retorno técnico e operacional.

- 🧽 **Pré-processamento e curadoria de dados** foram essenciais para o sucesso do projeto. A remoção de ruído, normalização de textos e balanceamento de classes influenciaram diretamente o desempenho dos modelos.

- 🔁 **Publicar modelos no Hugging Face Hub** simplificou o versionamento, o reuso e a colaboração, além de deixar o projeto mais organizado e acessível.

- 🎯 A escolha do modelo ideal deve considerar não apenas **métricas de performance**, mas também fatores como **custo computacional, facilidade de deploy, manutenção e interpretabilidade**.

# Setup do Ambiente & Dependências

## Instalações & Downloads

### Resumo

#### ⚙️ Instalação e Preparação do Ambiente

Antes de iniciar o processamento e a análise dos dados, o ambiente é configurado com as bibliotecas e recursos necessários para execução dos modelos e pré-processamento de texto.

#### 📦 Instalação de Pacotes
O projeto depende de uma série de bibliotecas para Processamento de Linguagem Natural, aprendizado de máquina e integração com modelos de linguagem avançados. Entre elas:

- `nltk`
- `spacy`
- `transformers`
- `huggingface_hub`
- `joblib`
- `wordcloud`
- `sentence-transformers`
- `tensorflow-text`
- `google-generativeai`
- `langchain-openai`

Também é realizado o comando `git lfs install` para suporte ao versionamento de arquivos grandes via Git LFS.

#### 🧹 Recursos do NLTK
São baixados recursos linguísticos essenciais para o pré-processamento de texto, como:

- Stopwords em português
- Tokenizadores (`punkt` e `punkt_tab`)

#### 🌍 Modelo Linguístico do spaCy
É feito o download do modelo de língua portuguesa `pt_core_news_md`, utilizado para análise lexical, lematização e outras tarefas de PLN com alta precisão.

### Código
"""

# Install required packages (suppressing output for brevity)
!pip install -q nltk spacy transformers huggingface_hub joblib wordcloud sentence-transformers tensorflow-text google-generativeai langchain-openai
!git lfs install

# Download NLTK stopwords (and any other required NLTK data)
import nltk
nltk.download("stopwords")
nltk.download("punkt")
nltk.download("punkt_tab")

# Download spaCy's Portuguese model
!python -m spacy download pt_core_news_md

"""## Imports & Configurações

### Resumo

#### 📚 Bibliotecas e Configurações Utilizadas

O projeto **NLP-Sentinel** faz uso de um ecossistema robusto de bibliotecas voltadas à análise de dados, Processamento de Linguagem Natural (PLN), aprendizado de máquina e uso de modelos de linguagem avançados (LLMs). A seguir, as categorias principais:

#### 📦 Manipulação de Dados e Visualização
Utiliza bibliotecas como **Pandas** e **NumPy** para organização e análise dos dados. Ferramentas como **Matplotlib**, **Seaborn** e **WordCloud** são usadas para criar visualizações e nuvens de palavras que facilitam a compreensão dos padrões de linguagem nas avaliações.

#### 🧹 Processamento de Linguagem Natural (PLN)
O pré-processamento textual é feito com **NLTK** e **spaCy**, realizando tokenização, remoção de stopwords, lematização e análise léxica. Também são utilizadas bibliotecas auxiliares para manipulação de textos e frequências de palavras.

#### 🔠 Embeddings e Modelos Pré-treinados
O projeto integra **Universal Sentence Encoder (USE)** por meio do TensorFlow Hub e modelos do **Sentence-Transformers** para gerar representações vetoriais semânticas. Além disso, emprega modelos pré-treinados como **BERT**, **DistilBERT** e **XLM-Roberta** utilizando a biblioteca **Transformers** da Hugging Face.

#### 🧠 Aprendizado de Máquina
Utiliza algoritmos e utilitários da **Scikit-learn** para tarefas de vetorização, classificação com SVM, modelagem de tópicos, avaliação de desempenho e pipelines de modelagem. Técnicas de otimização como busca em grade (Grid Search) também são aplicadas para aprimorar os modelos.

#### ⚙️ Modelagem com TensorFlow e Keras
Alguns testes exploratórios foram realizados com redes neurais utilizando **TensorFlow** e **Keras**, empregando camadas como LSTM, Dense e Dropout. A configuração inclui regularizações e parametrizações básicas para controle de treinamento.

#### 🤖 IA Generativa e In-Context Learning
A arquitetura moderna do projeto inclui o uso de **modelos generativos** em experimentos de *In-Context Learning*, com integração à **OpenAI (via LangChain)** e à **plataforma Gemini da Google**.

#### 🔐 Autenticação e Configurações
As **chaves de API** da Hugging Face, OpenAI e Google são acessadas com segurança através de variáveis armazenadas no ambiente do Google Colab. O projeto também define parâmetros globais para padronizar o número de épocas e o tamanho dos lotes durante os testes de modelos.

### Código
"""

# Import core libraries for data handling, visualization, and machine learning
import os
import shutil
import subprocess
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import string
import tensorflow as tf

# NLP and text processing libraries
from nltk.corpus import stopwords
from nltk import word_tokenize
from wordcloud import WordCloud
import spacy
from collections import Counter

# Transformers and Hugging Face related libraries
from transformers import BertTokenizer, TFBertForSequenceClassification, AdamWeightDecay, DistilBertTokenizer, TFDistilBertForSequenceClassification, XLMRobertaTokenizer, TFXLMRobertaForSequenceClassification
import joblib
from huggingface_hub import create_repo, Repository
from sentence_transformers import SentenceTransformer

# Additional libraries for In-Context Learning experiments
import google.generativeai as genai
from langchain_openai import ChatOpenAI

# TensorFlow Text (required for Universal Sentence Encoder, etc.)
import tensorflow_text as text

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Layer, Bidirectional, Embedding, SimpleRNN, Dense, Dropout, Input
from tensorflow.keras import regularizers
import tensorflow_hub as hub

from tensorflow.keras.layers import LSTM

# Sklearn
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.model_selection import train_test_split

from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score, ConfusionMatrixDisplay

from sklearn.preprocessing import StandardScaler

# Google Colab
from google.colab import userdata

# Get Hugging Face token from Secrets
hf_token = userdata.get('HUGGING_FACE_TOKEN')

# Get OpenAI API Key from Secrets
os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')

# Retorna a chave de API do Google Gemini do userdata
myKey = userdata.get('GOOGLE_API_KEY')

# Set global configuration parameters
DEFAULT_EPOCHS = 1
DEFAULT_BATCH_SIZE = 32

print("Environment setup complete. All dependencies have been installed and imported.")

"""# Carregamento dos Dados & Exploração Inicial

### Resumo

#### 🧾 Carregamento e Inspeção dos Dados

O projeto inicia com o carregamento e a inspeção exploratória do conjunto de dados, garantindo que os dados estejam íntegros e prontos para as etapas seguintes de pré-processamento e modelagem.

#### 📥 Fonte dos Dados
O dataset utilizado está disponível publicamente no GitHub e é carregado diretamente via URL no formato `.csv`. Ele contém avaliações textuais e notas atribuídas por clientes de e-commerce no Brasil.

#### 🔍 Carregamento do Dataset
Uma função é utilizada para ler o arquivo CSV e armazenar os dados em um `DataFrame` do Pandas. Ao final do processo, uma mensagem de confirmação é exibida indicando que os dados foram carregados com sucesso.

#### 📊 Inspeção Inicial dos Dados
Uma segunda função realiza uma inspeção básica do `DataFrame`, exibindo:
- Informações gerais sobre colunas e tipos de dados
- Estatísticas descritivas (inclusive para variáveis categóricas)
- As 5 primeiras linhas do conjunto de dados

Essa etapa é essencial para entender a estrutura dos dados e orientar decisões sobre tratamento posterior.

#### 🚨 Verificação de Dados Ausentes e Inconsistentes
Também é feita uma análise para detectar:
- **Valores nulos (NaN)** por coluna
- **Campos vazios** representados por strings em branco

Esses diagnósticos ajudam a identificar possíveis problemas de qualidade nos dados e guiam o pré-processamento necessário antes da vetorização e classificação.

### Código
"""

def load_data(url: str) -> pd.DataFrame:
    """
    Loads a CSV dataset from the provided URL.

    Args:
        url (str): URL of the CSV file.

    Returns:
        pd.DataFrame: Loaded dataset.
    """
    df = pd.read_csv(url)
    print("Dataset loaded successfully!")
    return df

def inspect_data(df: pd.DataFrame):
    """
    Displays basic information about the DataFrame including data types, summary statistics,
    and the first few rows.

    Args:
        df (pd.DataFrame): DataFrame to inspect.
    """
    print("\n--- DataFrame Info ---")
    df.info()

    print("\n--- Descriptive Statistics (All Columns) ---")
    # For comprehensive statistics including categorical variables
    display(df.describe(include='all'))

    print("\n--- First 5 Rows of the DataFrame ---")
    display(df.head())

def check_missing_and_inconsistencies(df: pd.DataFrame):
    """
    Checks and prints the count of missing values and empty strings in the DataFrame.

    Args:
        df (pd.DataFrame): DataFrame to check.
    """
    print("\n--- Missing Values by Column ---")
    nan_counts = df.isnull().sum()
    nan_counts = nan_counts[nan_counts > 0]
    print(nan_counts)

    print("\n--- Empty String Counts by Column ---")
    empty_counts = df.apply(lambda col: (col.astype(str).str.strip() == "").sum())
    empty_counts = empty_counts[empty_counts > 0]
    print(empty_counts)

# URL of the dataset
data_url = "https://raw.githubusercontent.com/lucianoayres/filebin/refs/heads/main/olist_order_reviews_dataset.csv"

# Load the dataset
df_new = load_data(data_url)

# Perform basic inspection of the data
inspect_data(df_new)

# Check for missing values and inconsistent data (empty strings)
check_missing_and_inconsistencies(df_new)

"""# Limpeza dos Dados & Pré-processamento

### Resumo

#### 🧼 Limpeza, Transformação e Mapeamento de Sentimentos

Após o carregamento inicial, os dados passam por diversas etapas de padronização, filtragem e transformação para garantir consistência e qualidade antes da vetorização e classificação.

#### 📊 Estatísticas em Cada Etapa
Em diferentes pontos do processo, são exibidas estatísticas básicas do dataset:
- Quantidade total de linhas
- Valores ausentes por coluna
- Distribuição da coluna `rating` (quando disponível)

Essas estatísticas são úteis para acompanhar a evolução dos dados ao longo das etapas de tratamento.

#### 🏷️ Renomeação e Combinação de Colunas
As colunas do dataset são renomeadas para nomes padronizados. Além disso:
- Os campos `review_comment_title` e `review_comment_message` são combinados em uma única coluna `review`.
- Essa fusão garante que tanto o título quanto o comentário sejam considerados na análise de sentimento.

#### 🧹 Filtragem de Dados Inválidos
Várias regras são aplicadas para eliminar registros irrelevantes ou inconsistentes:
- Remoção de avaliações com nota 3 (consideradas neutras ou ambíguas)
- Conversão e validação de ratings como valores numéricos
- Eliminação de comentários vazios ou compostos apenas por espaços
- Restrição a ratings válidos: **1, 2, 4, 5**

Essas ações visam deixar o conjunto mais limpo e orientado à classificação binária.

#### ❤️ Mapeamento de Ratings para Sentimentos
Os ratings são transformados em duas novas colunas:
- **`sentiment`**: etiqueta textual (`positivo` ou `negativo`)
- **`polarity`**: valor binário (1 para positivo, 0 para negativo)

Essa transformação facilita a aplicação de algoritmos supervisionados e serve como base para avaliação dos modelos.

#### 💾 Salvamento do Dataset Final
O conjunto de dados final, devidamente limpo e rotulado, é exportado para um novo arquivo CSV. Esse arquivo servirá como base para as próximas etapas de vetorização, modelagem e avaliação de desempenho.

### Código
"""

def print_stats(df: pd.DataFrame, stage: str = ""):
    """
    Imprime estatísticas básicas do DataFrame, incluindo:
      - Número total de linhas
      - Quantidade de valores ausentes por coluna
      - Distribuição da coluna 'rating', se existir

    Args:
        df (pd.DataFrame): DataFrame a ser analisado.
        stage (str): Descrição do estágio (ex: "Dados Originais", "Após Filtragem", etc.)
    """
    print(f"--- Estatísticas {stage} ---")
    print(f"Total de linhas: {len(df)}")
    print("Valores ausentes por coluna:")
    print(df.isnull().sum())
    if "rating" in df.columns:
        print("Distribuição de ratings:")
        print(df["rating"].value_counts())
    print("-" * 40)


def rename_and_combine_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Renomeia as colunas para nomes padronizados e combina 'review_title' e 'review_comment_message'
    em uma única coluna 'review'.

    Args:
        df (pd.DataFrame): DataFrame original.

    Retorna:
        pd.DataFrame: DataFrame com colunas renomeadas e review combinada.
    """
    # Renomeia as colunas
    df = df.rename(columns={
        "review_comment_message": "review",
        "review_comment_title": "review_title",
        "review_score": "rating"
    })

    # Função para combinar título e review
    def combine_review(row):
        title = str(row["review_title"]) if not pd.isnull(row["review_title"]) else ""
        review = str(row["review"]) if not pd.isnull(row["review"]) else ""
        if review.strip() != "":
            if title.strip() != "":
                return title.strip() + ". " + review.strip()
            else:
                return review.strip()
        else:
            return title.strip()

    df["review"] = df.apply(combine_review, axis=1)

    # Mantém apenas as colunas necessárias
    df = df[["review", "rating"]]
    return df


def filter_invalid_data(df: pd.DataFrame) -> pd.DataFrame:
    """
    Filtra os dados removendo:
      - Linhas com rating igual a 3 (considerado neutro/outlier)
      - Ratings não numéricos
      - Linhas com reviews vazias ou compostas apenas por espaços
      - Ratings que não estão no conjunto válido [1, 2, 4, 5]

    Args:
        df (pd.DataFrame): DataFrame de entrada.

    Retorna:
        pd.DataFrame: DataFrame limpo após a filtragem.
    """
    # Cria uma cópia para evitar SettingWithCopyWarning
    df = df.copy()

    # Remove linhas com rating igual a 3
    df = df[df["rating"] != 3]

    # Garante que 'rating' seja numérico; converte erros para NaN e remove linhas com NaN
    df.loc[:, "rating"] = pd.to_numeric(df["rating"], errors='coerce')
    df = df.dropna(subset=["rating"])

    # Remove linhas com reviews vazias (após remover espaços)
    df = df[~df["review"].apply(lambda x: isinstance(x, str) and x.strip() == "")]

    # Filtra para manter apenas ratings válidos (1, 2, 4, 5)
    valid_ratings = [1, 2, 4, 5]
    df = df[df["rating"].isin(valid_ratings)]

    return df


def map_ratings_to_labels(df: pd.DataFrame) -> pd.DataFrame:
    """
    Converte os ratings numéricos em labels de sentimento e cria uma coluna de polaridade binária.
    Ratings maiores ou iguais a 4 são considerados 'positivo'; ratings menores ou iguais a 2 são 'negativo'.

    Args:
        df (pd.DataFrame): DataFrame com a coluna 'rating'.

    Retorna:
        pd.DataFrame: DataFrame com as colunas 'sentiment' e 'polarity' adicionadas.
    """
    def convert_to_sentiment(rating):
        return "positivo" if rating >= 4 else "negativo"

    def convert_to_polarity(rating):
        return 1 if rating >= 4 else 0

    df["sentiment"] = df["rating"].apply(convert_to_sentiment)
    df["polarity"] = df["rating"].apply(convert_to_polarity)
    return df

print_stats(df_new, "Dados Originais")

"""#### 1. Renomear e combinar colunas

"""

df_clean = rename_and_combine_columns(df_new)
print_stats(df_clean, "Após Renomear e Combinar Colunas")

"""#### 2. Filtrar dados inválidos"""

df_clean = filter_invalid_data(df_clean)
print_stats(df_clean, "Após Filtragem de Dados Inválidos")

"""#### 3. Mapear ratings para labels e polaridade"""

df_clean = map_ratings_to_labels(df_clean)
print_stats(df_clean, "Após Mapeamento de Ratings para Sentimentos")

"""#### 4. Salvar os dados limpos para referência futura

"""

df_clean.to_csv("olist_order_reviews_dataset.csv", index=False)

"""#### 5. Exibir Amostra do Dataframe Final Após a Limpeza"""

# Atualiza o DataFrame principal
df = df_clean

# Exibe as primeiras linhas do DataFrame final limpo
display(df.head())

"""# Análise Descritiva

### Resumo

#### 📊 Análise Exploratória dos Dados (EDA)

Após a preparação do dataset, é realizada uma análise exploratória detalhada para entender padrões, variações e correlações nos dados de avaliação dos consumidores.

---

#### 📈 Distribuição das Notas (Ratings)
Um gráfico de barras exibe a frequência de cada nota (de 1 a 5), permitindo visualizar o desequilíbrio de classes no conjunto de dados. Também são listados os totais de avaliações por nota.

---

#### 📏 Análise do Comprimento das Avaliações
Foram calculadas duas métricas para cada comentário:
- **Número de caracteres**
- **Número de palavras**

Essas métricas foram visualizadas em histogramas e boxplots, segmentados por sentimento (positivo/negativo), para observar diferenças na extensão textual conforme a polaridade da avaliação.

---

#### ☁️ Nuvens de Palavras (Word Clouds)
Foram geradas nuvens de palavras separadas para avaliações positivas e negativas. Essa visualização qualitativa revela as palavras mais recorrentes em cada polaridade, ajudando a entender o vocabulário típico dos consumidores satisfeitos e insatisfeitos.

---

#### 📉 Relação entre Comprimento e Nota
Um gráfico de dispersão com linha de regressão mostra a correlação entre o número de caracteres das avaliações e a nota atribuída. O coeficiente de correlação de Pearson também é calculado para quantificar essa relação.

---

#### 🧾 Extração de Entidades Nomeadas (NER)
Usando o modelo de linguagem do **spaCy**, foram extraídas entidades nomeadas como organizações, pessoas, locais e produtos. As 20 entidades mais mencionadas nas avaliações são exibidas em um gráfico de barras.

---

#### 🧠 Riqueza Lexical
Foram calculadas as seguintes métricas para cada review:
- Total de palavras (`word_count`)
- Palavras únicas (`unique_word_count`)
- Taxa de diversidade lexical (TTR – *Type-Token Ratio*)

Estatísticas descritivas dessas métricas foram analisadas, além da média de palavras por sentimento e um histograma comparativo.

---

#### 🔡 Análise de N-gramas (Bigrams e Trigrams)
A análise de n-gramas permite identificar combinações de palavras frequentes:
- **Top 10 bigramas** (ex: "entrega rápida", "produto bom")
- **Top 10 trigramas** (ex: "muito bom produto")

Essa técnica ajuda a identificar frases recorrentes e expressões comuns nas avaliações.

---

#### 🧵 Modelagem de Tópicos (LDA)
Com o uso de **Latent Dirichlet Allocation (LDA)**, foram identificados **cinco tópicos** principais dentro das avaliações, destacando palavras-chave associadas a cada grupo temático.

---

#### 🔗 Matriz de Correlação
Foi construída uma matriz de correlação entre variáveis numéricas como:
- Nota (rating)
- Polaridade (binária)
- Total de palavras
- TTR

Essa matriz foi visualizada em formato de **heatmap** para facilitar a interpretação visual das relações entre variáveis.

---

Essa análise exploratória fornece uma base sólida para interpretar o comportamento dos consumidores e embasar as decisões de modelagem no projeto.

### Código

#### 1. Distribuição das Notas
"""

plt.figure(figsize=(8, 6))
ax = sns.countplot(x='rating', data=df, hue='rating', palette='pastel')
if ax.get_legend() is not None:
    ax.get_legend().remove()  # Remove legend to avoid duplication
plt.title('Distribuição das Notas')
plt.xlabel('Nota')
plt.ylabel('Frequência')
plt.show()

rating_counts = df['rating'].value_counts().sort_index()
print("Resultados Totais da Distribuição das Notas:")
for rating, count in rating_counts.items():
    print(f"Nota {rating}: {count} avaliações")

"""#### 2. Análise do Comprimento das Avaliações (Caracteres e Palavras)

"""

df['review_length_chars'] = df['review'].str.len()
df['review_length_words'] = df['review'].str.split().apply(len)

plt.figure(figsize=(8, 6))
plt.hist(df['review_length_chars'], bins=50, color='skyblue', edgecolor='black')
plt.title('Histograma do Comprimento das Avaliações (Caracteres)')
plt.xlabel('Número de caracteres')
plt.ylabel('Frequência')
plt.show()

plt.figure(figsize=(8, 6))
plt.hist(df['review_length_words'], bins=50, color='lightcoral', edgecolor='black')
plt.title('Histograma do Comprimento das Avaliações (Palavras)')
plt.xlabel('Número de palavras')
plt.ylabel('Frequência')
plt.show()

"""#### 3. Box Plot do Comprimento das Avaliações por Sentimento

"""

plt.figure(figsize=(8, 6))
ax = sns.boxplot(x='sentiment', y='review_length_chars', data=df, hue='sentiment', palette='pastel')
if ax.get_legend() is not None:
    ax.get_legend().remove()  # Remove the legend if it exists
plt.title('Distribuição do Comprimento das Avaliações por Sentimento (Caracteres)')
plt.xlabel('Sentimento')
plt.ylabel('Número de caracteres')
plt.show()

plt.figure(figsize=(8, 6))
ax = sns.boxplot(x='sentiment', y='review_length_words', data=df, hue='sentiment', palette='pastel')
if ax.get_legend() is not None:
    ax.get_legend().remove()  # Remove the legend if it exists
plt.title('Distribuição do Comprimento das Avaliações por Sentimento (Palavras)')
plt.xlabel('Sentimento')
plt.ylabel('Número de palavras')
plt.show()

"""#### 4. Nuvens de Palavras para Avaliações Positivas e Negativas"""

def generate_wordcloud(text, title):
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)
    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.title(title)
    plt.show()

# Use a coluna 'clean_review' se estiver disponível; caso contrário, utilize 'review'
if 'clean_review' in df.columns:
    pos_text = ' '.join(df[df['sentiment'] == 'positivo']['clean_review'])
    neg_text = ' '.join(df[df['sentiment'] == 'negativo']['clean_review'])
else:
    pos_text = ' '.join(df[df['sentiment'] == 'positivo']['review'])
    neg_text = ' '.join(df[df['sentiment'] == 'negativo']['review'])

generate_wordcloud(pos_text, "Nuvem de Palavras - Avaliações Positivas")

generate_wordcloud(neg_text, "Nuvem de Palavras - Avaliações Negativas")

"""#### 5. Análise de Correlação: Comprimento da Avaliação vs. Nota

"""

plt.figure(figsize=(8, 6))
sns.regplot(x='review_length_chars', y='rating', data=df, scatter_kws={'alpha':0.5}, line_kws={'color':'red'})
plt.title('Relação entre Comprimento da Avaliação e Nota')
plt.xlabel('Número de caracteres')
plt.ylabel('Nota')
plt.show()

correlation = df['review_length_chars'].corr(df['rating'])
print(f"Coeficiente de correlação de Pearson entre comprimento e nota: {correlation:.2f}")

"""#### 6. Análise de Entidades Nomeadas (NER)"""

nlp = spacy.load('pt_core_news_md')

def extract_entities(text):
    doc = nlp(text)
    # Seleciona entidades de interesse (ex.: ORGANIZAÇÃO, PESSOA, LOCAL, PRODUTO)
    return [ent.text for ent in doc.ents if ent.label_ in ['ORG', 'PERSON', 'LOC', 'PRODUCT']]

df['entities'] = df['review'].astype(str).apply(extract_entities)
all_entities = [entity for sublist in df['entities'] for entity in sublist]
entity_freq = Counter(all_entities).most_common(20)
entities_df = pd.DataFrame(entity_freq, columns=['Entidade', 'Frequência'])

plt.figure(figsize=(12, 8))
ax = sns.barplot(x='Frequência', y='Entidade', data=entities_df, hue='Entidade', palette='viridis')
if ax.get_legend() is not None:
    ax.get_legend().remove()  # Remove the legend if it exists
plt.title('Top 20 Entidades Nomeadas Mais Frequentes')
plt.xlabel('Frequência')
plt.ylabel('Entidade')
plt.tight_layout()
plt.show()

"""#### 7. Riqueza Léxica & Legibilidade"""

def compute_lexical_metrics(text: str):
    # Basic tokenization
    tokens = nltk.word_tokenize(text.lower())
    num_words = len(tokens)
    unique_words = set(tokens)
    num_unique = len(unique_words)
    ttr = num_unique / num_words if num_words > 0 else 0
    return num_words, num_unique, ttr

df["word_count"] = 0
df["unique_word_count"] = 0
df["ttr"] = 0.0

for i, row in df.iterrows():
    wc, uwc, ttr_value = compute_lexical_metrics(row["review"])
    df.at[i, "word_count"] = wc
    df.at[i, "unique_word_count"] = uwc
    df.at[i, "ttr"] = ttr_value

# Summarize these new columns
print("\n--- Lexical Richness Summary ---")
print(df[["word_count", "unique_word_count", "ttr"]].describe())

# Compare average word count by sentiment
avg_word_count = df.groupby("sentiment")["word_count"].mean()
print("\n--- Average Word Count by Sentiment ---")
print(avg_word_count)

# Optional: Visualize word count distribution
plt.figure(figsize=(8, 6))
sns.histplot(data=df, x="word_count", hue="sentiment", bins=50, kde=True)
plt.title("Distribuição do Número de Palavras por Sentimento")
plt.xlabel("Número de Palavras")
plt.ylabel("Frequência")
plt.show()

"""#### 8. Análise Avançada de Bigramas & Trigramas"""

def get_top_ngrams(corpus, n=2, top_k=10):
    """
    Returns the top_k n-grams of length n from the corpus based on raw frequency.
    """
    vec = CountVectorizer(ngram_range=(n, n), stop_words=None)  # Use 'portuguese' if you want built-in stopwords
    bag_of_words = vec.fit_transform(corpus)
    sum_words = bag_of_words.sum(axis=0)
    words_freq = [(word, sum_words[0, idx]) for word, idx in vec.vocabulary_.items()]
    words_freq = sorted(words_freq, key=lambda x: x[1], reverse=True)
    return words_freq[:top_k]

# Prepare corpus (lowercased reviews)
corpus = df["review"].apply(lambda x: x.lower()).tolist()

top_10_bigrams = get_top_ngrams(corpus, n=2, top_k=10)
top_10_trigrams = get_top_ngrams(corpus, n=3, top_k=10)

print("\n--- Top 10 Bigrams ---")
for phrase, freq in top_10_bigrams:
    print(f"{phrase}: {freq}")

print("\n--- Top 10 Trigrams ---")
for phrase, freq in top_10_trigrams:
    print(f"{phrase}: {freq}")

"""#### 9. Modelagem Básica de Tópicos"""

# Convert text to a matrix of token counts
vectorizer = CountVectorizer(stop_words=None, max_features=5000)  # Adjust max_features as needed
X = vectorizer.fit_transform(corpus)

# Fit LDA with, for example, 5 topics
lda = LatentDirichletAllocation(n_components=5, random_state=42)
lda.fit(X)

# Print top words in each topic
def display_topics(model, feature_names, no_top_words=10):
    for idx, topic in enumerate(model.components_):
        print(f"\nTopic {idx + 1}:")
        top_features_idx = topic.argsort()[:-no_top_words - 1:-1]
        top_features = [feature_names[i] for i in top_features_idx]
        print(" ".join(top_features))

feature_names = vectorizer.get_feature_names_out()
display_topics(lda, feature_names, no_top_words=10)

"""#### 10. Análise de Correlação entre Variáveis Numéricas"""

# We'll create a numeric subset of df for correlation
numeric_subset = df[["rating", "polarity", "word_count", "ttr"]].copy()

# Compute correlation matrix
corr_matrix = numeric_subset.corr()

print("\n--- Correlation Matrix ---")
print(corr_matrix)

# Visualize correlation matrix
plt.figure(figsize=(6, 5))
sns.heatmap(corr_matrix, annot=True, cmap="Blues", fmt=".2f")
plt.title("Correlação entre Variáveis Numéricas")
plt.show()

"""# Divisão do Dataset

### Resumo

#### 🧪 Divisão do Conjunto de Dados

#### 🔄 Separação em Dados de Treinamento e Teste

Para avaliar o desempenho dos modelos de classificação de forma justa, o conjunto de dados foi dividido em dois subconjuntos:

- **80%** para **treinamento**
- **20%** para **teste**

A divisão é feita de forma aleatória, mas com um valor fixo de `random_state` para garantir reprodutibilidade dos experimentos. Essa separação permite treinar os modelos com uma porção dos dados e, posteriormente, testá-los com exemplos nunca vistos, garantindo uma avaliação mais realista da generalização do modelo.

### Código
"""

X_train, X_test, y_train, y_test = train_test_split(
    df["review"],
    df["polarity"],
    test_size=0.2,
    random_state=42
)

"""# Declaração de Funções Úteis

### Resumo

#### ☁️ Publicação de Modelos no Hugging Face Hub

O projeto inclui utilitários para salvar modelos treinados localmente e publicá-los diretamente no **Hugging Face Hub**, permitindo fácil reuso, versionamento e compartilhamento com a comunidade.

---

#### 💾 Upload de Modelos Keras e Transformers

Para modelos baseados em **TensorFlow/Keras** ou **Transformers**, é utilizada a função `save_model_to_hf()`, que realiza as seguintes etapas:

- Clona o repositório do Hugging Face na máquina local
- Cria o arquivo `.gitattributes` para habilitar o uso do Git LFS (armazenamento de arquivos grandes)
- Salva o modelo no formato adequado:
  - `.keras` ou `.h5` para modelos Keras
  - `save_pretrained()` para modelos Transformers
- Realiza o commit e o push automático para o repositório remoto no Hugging Face

A função é flexível, permitindo alternar entre modelos Keras e Transformers por meio do parâmetro `is_transformer`.

---

#### 🧠 Upload de Modelos Scikit-learn

Para modelos treinados com **Scikit-learn**, é utilizada a função `save_sklearn_model_to_hf()` que:

- Serializa o modelo usando `joblib`
- Cria ou clona o repositório desejado no Hugging Face Hub
- Copia o modelo para o diretório local do repositório
- Realiza o commit e push automático para disponibilizar o modelo

Essa abordagem permite versionar e publicar modelos de classificação tradicionais (como SVM), mantendo a consistência com o restante do ecossistema Hugging Face.

---

Essas funções automatizam completamente o processo de publicação de modelos, reduzindo o esforço manual e facilitando a reutilização e o compartilhamento dos experimentos desenvolvidos no projeto.

### Código
"""

def save_model_to_hf(model, local_dir, file_name, repo_id, is_transformer=False):
    """
    Clones the repo into `local_dir`, creates a .gitattributes file to track large files (for Keras models),
    saves the model inside `local_dir`, and pushes to the HF Hub.

    Args:
      model: the trained model (a Keras model or a Transformers model)
      local_dir: local directory to clone the repository into (will be overwritten if it exists)
      file_name: the file name (for Keras models, e.g. "rnn_model.keras")
      repo_id: the Hugging Face repository ID (e.g., "layers2024/rnn-sentiment")
      is_transformer: if True, uses model.save_pretrained(); otherwise uses model.save()
    """
    subprocess.run(["git", "lfs", "install"], check=True)

    if os.path.exists(local_dir):
        shutil.rmtree(local_dir)

    create_repo(repo_id=repo_id, exist_ok=True, token=hf_token)

    repo = Repository(local_dir=local_dir, clone_from=repo_id, use_auth_token=hf_token)

    if not is_transformer:
        attributes_path = os.path.join(local_dir, ".gitattributes")
        with open(attributes_path, "w") as f:
            f.write("*.keras filter=lfs diff=lfs merge=lfs -text\n")
            f.write("*.h5 filter=lfs diff=lfs merge=lfs -text\n")
        repo.git_add(".gitattributes")
        repo.push_to_hub(commit_message="Add .gitattributes for Git LFS", blocking=True)

    save_path = os.path.join(local_dir, file_name)
    if not is_transformer:
        if not (save_path.endswith(".keras") or save_path.endswith(".h5")):
            save_path += ".keras"
        model.save(save_path)
    else:
        model.save_pretrained(save_path)

    repo.git_add()
    repo.push_to_hub(commit_message="Add trained model", blocking=True)

def save_sklearn_model_to_hf(model, file_path, repo_id):
    """
    Serializes a scikit-learn model using joblib and pushes it to the Hugging Face Hub.

    Args:
      model: The scikit-learn model to be saved.
      file_path: The local file path to save the model (e.g., "svm_sentencebert_model.joblib").
      repo_id: The Hugging Face repository ID (e.g., "layers2024/svm-sentencebert-sentiment").
    """
    dir_name = os.path.dirname(file_path)
    if dir_name and not os.path.exists(dir_name):
        os.makedirs(dir_name)

    joblib.dump(model, file_path)

    create_repo(repo_id=repo_id, exist_ok=True, token=hf_token)

    temp_dir = "temp_repo"
    if os.path.exists(temp_dir):
        shutil.rmtree(temp_dir)

    repo = Repository(local_dir=temp_dir, clone_from=repo_id, use_auth_token=hf_token)

    shutil.copy(file_path, os.path.join(temp_dir, os.path.basename(file_path)))

    repo.git_add(os.path.basename(file_path))
    repo.push_to_hub(commit_message="Save scikit-learn model", blocking=True)

"""# Classificação com Modelos Transformers e Embeddings Contextuais

## BERT para Classificação

### Resumo

#### 🤖 Classificação de Sentimentos com BERT (Português)

Nesta etapa, o projeto utiliza o modelo **BERT pré-treinado para português** da Neuralmind, hospedado no Hugging Face Hub, para classificar sentimentos em avaliações de consumidores.

---

#### 🔠 Tokenização e Preparação dos Dados
- As avaliações de treino e teste são tokenizadas com `BertTokenizer`, utilizando padding e truncamento automáticos.
- As entradas são convertidas em tensores compatíveis com o TensorFlow para alimentar o modelo BERT.

---

#### ⚖️ Balanceamento de Classes
Para lidar com o desbalanceamento entre avaliações positivas e negativas, são calculados **pesos de classe** com base na distribuição do conjunto de treino. Esses pesos são aplicados manualmente na função de perda para penalizar classes minoritárias de forma adequada.

---

#### 🧠 Treinamento do Modelo
O modelo `TFBertForSequenceClassification` é treinado utilizando:
- Otimizador **AdamWeightDecay**
- Função de perda ponderada personalizada
- Métrica de avaliação `SparseCategoricalAccuracy`
- Ciclo de treinamento implementado manualmente com `GradientTape`, proporcionando mais controle sobre o processo

A quantidade de épocas e o tamanho dos lotes são definidos por parâmetros globais (`DEFAULT_EPOCHS`, `DEFAULT_BATCH_SIZE`).

---

#### 🧪 Avaliação do Modelo
Após o treinamento, o modelo é avaliado com os dados de teste. As métricas de avaliação incluem:
- **Loss** (função de perda)
- **Acurácia**
- **F1 Score (ponderado)**

Além disso, é exibida uma **matriz de confusão** para visualizar a performance do modelo em relação à polaridade (positivo/negativo).

---

#### ☁️ Publicação no Hugging Face Hub
Ao final do processo, o modelo BERT treinado é salvo e publicado no **Hugging Face Hub** através da função `save_model_to_hf()`, garantindo que ele possa ser reutilizado e compartilhado com a comunidade. O upload utiliza o Git LFS para arquivos grandes e segue as boas práticas de versionamento.

---

Este modelo BERT representa uma abordagem moderna e poderosa para tarefas de **classificação binária de sentimentos**, aproveitando o poder dos LLMs com o suporte completo à língua portuguesa.

### Código
"""

tokenizer = BertTokenizer.from_pretrained("neuralmind/bert-base-portuguese-cased")
model = TFBertForSequenceClassification.from_pretrained(
    "neuralmind/bert-base-portuguese-cased",
    num_labels=2  # binary: negativo (0), positivo (1)
)

X_train_tokens = tokenizer(list(X_train), padding=True, truncation=True, return_tensors="tf")
X_test_tokens = tokenizer(list(X_test), padding=True, truncation=True, return_tensors="tf")

counts = np.array([
    np.sum(y_train == 0),  # negativo
    np.sum(y_train == 1)   # positivo
])
total = counts.sum()
class_weights = {i: total / count for i, count in enumerate(counts)}
print("Class weights:", class_weights)

def weighted_loss(y_true, y_pred):
    losses = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)
    weights_tensor = tf.constant([class_weights[0], class_weights[1]], dtype=tf.float32)
    sample_weights = tf.gather(weights_tensor, tf.cast(y_true, tf.int32))
    return tf.reduce_mean(losses * sample_weights)

optimizer = AdamWeightDecay(learning_rate=3e-5)
metric = tf.keras.metrics.SparseCategoricalAccuracy()

@tf.function
def train_step(inputs, targets):
    with tf.GradientTape() as tape:
        predictions = model(inputs)
        loss = weighted_loss(targets, predictions.logits)
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    metric.update_state(targets, predictions.logits)
    return loss, metric.result()

y_train_array = y_train.to_numpy()

epochs = DEFAULT_EPOCHS
batch_size = DEFAULT_BATCH_SIZE

for epoch in range(epochs):
    print(f"\nEpoch {epoch + 1}/{epochs}")
    metric.reset_state()
    for i in range(0, len(X_train), batch_size):
        batch_inputs = {k: v[i:i + batch_size] for k, v in X_train_tokens.data.items()}
        batch_targets = y_train_array[i:i + batch_size]
        loss, accuracy = train_step(batch_inputs, batch_targets)
        print(f"Batch {i // batch_size + 1}: Loss = {loss:.4f}, Accuracy = {accuracy:.4f}")

"""#### Avaliação dos Resultados para o BERT"""

batch_size = 32 if 'DEFAULT_BATCH_SIZE' not in globals() else DEFAULT_BATCH_SIZE
all_predictions = []

for i in range(0, len(X_test), batch_size):
    batch_inputs = {k: v[i:i + batch_size] for k, v in X_test_tokens.data.items()}
    batch_logits = model(batch_inputs).logits
    all_predictions.append(batch_logits)

predictions = tf.concat(all_predictions, axis=0)
predicted_labels = np.argmax(predictions, axis=1)

y_test_adjusted = y_test.values

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss = loss_fn(y_test_adjusted, predictions).numpy()

accuracy_bert = accuracy_score(y_test_adjusted, predicted_labels)
f1_bert = f1_score(y_test_adjusted, predicted_labels, average='weighted')

print("\nBERT:")
print(f"Test Loss: {loss:.4f}")
print(f"Acurácia: {accuracy_bert:.4f}")
print(f"F1 Score: {f1_bert:.4f}")

"""#### Matriz de Confusão para o BERT"""

def plot_confusion_matrix(y_true, y_pred, title="Confusion Matrix"):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=["negativo", "positivo"],
                yticklabels=["negativo", "positivo"])
    plt.title(title)
    plt.xlabel("Predicted Label")
    plt.ylabel("True Label")
    plt.show()

plot_confusion_matrix(y_test_adjusted, predicted_labels, title="Confusion Matrix - BERT (Polarity)")

print("Saving BERT model to HF Hub...")
save_model_to_hf(
    model=model,
    local_dir="bert_model",
    file_name="",
    repo_id="layers2024/bert-sentiment",
    is_transformer=True
)
print("BERT model successfully pushed to HF Hub!")

"""## DistilBERT para Classificação

### Resumo

#### 🌍 Classificação de Sentimentos com DistilBERT Multilíngue

Além do BERT em português, o projeto também explora o uso do **DistilBERT multilíngue**, uma versão leve e eficiente de BERT que suporta múltiplos idiomas, incluindo o português.

---

#### 🔠 Tokenização e Preparação dos Dados
- Os dados são processados com o `DistilBertTokenizer`, convertendo os textos em tensores de entrada apropriados para o modelo.
- Padding e truncamento são aplicados automaticamente para lidar com variações no comprimento dos textos.

---

#### ⚖️ Balanceamento de Classes
Assim como no BERT, são calculados **pesos de classe** com base na proporção de exemplos positivos e negativos no dataset. Esses pesos são aplicados na função de perda para garantir um treinamento mais justo.

---

#### 🧠 Treinamento do Modelo
O modelo `TFDistilBertForSequenceClassification` é treinado com:
- Otimizador **AdamWeightDecay**
- Função de perda personalizada ponderada
- Métrica de acurácia com `SparseCategoricalAccuracy`
- Treinamento manual com `GradientTape`, permitindo controle completo sobre os passos de backpropagation

O treinamento é executado com o número de épocas e tamanho de batch definidos pelos parâmetros globais do projeto.

---

#### 🧪 Avaliação do Modelo
Após o treinamento, o modelo DistilBERT é testado e avaliado com base em:

- **Acurácia**
- **F1 Score ponderado**
- **Relatório de classificação** completo
- **Matriz de confusão** para visualização dos acertos e erros por classe

Essas métricas permitem comparar seu desempenho com outras abordagens, como o modelo BERT em português.

---

#### ☁️ Publicação no Hugging Face Hub
Ao final do processo, o modelo treinado é salvo e publicado automaticamente no **Hugging Face Hub**. Essa integração facilita a reutilização do modelo em outros projetos e experimentos, além de permitir o versionamento do progresso.

---

O uso do **DistilBERT multilíngue** permite avaliar a capacidade de generalização de modelos mais leves em contextos reais de classificação de sentimentos, com ótimo custo-benefício computacional.

### Código
"""

tokenizer_distil = DistilBertTokenizer.from_pretrained("distilbert-base-multilingual-cased")
model_distil = TFDistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-multilingual-cased", num_labels=2  # binary: negativo vs positivo
)

X_train_tokens_distil = tokenizer_distil(list(X_train), padding=True, truncation=True, return_tensors="tf")
X_test_tokens_distil = tokenizer_distil(list(X_test), padding=True, truncation=True, return_tensors="tf")

optimizer_distil = AdamWeightDecay(learning_rate=3e-5)
metric_distil = tf.keras.metrics.SparseCategoricalAccuracy()

counts = np.array([
    df[df["polarity"] == 0].shape[0],  # negativo
    df[df["polarity"] == 1].shape[0]   # positivo
])
total = counts.sum()
class_weights = {i: total / count for i, count in enumerate(counts)}
print("Class weights:", class_weights)

weights_tensor = tf.constant([class_weights[0], class_weights[1]], dtype=tf.float32)

def weighted_loss(y_true, y_pred):
    losses = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)
    sample_weights = tf.gather(weights_tensor, tf.cast(y_true, tf.int32))
    return tf.reduce_mean(losses * sample_weights)

def train_step_distil(inputs, targets):
    with tf.GradientTape() as tape:
        outputs = model_distil(inputs)
        logits = outputs.logits
        loss = weighted_loss(targets, logits)
    gradients = tape.gradient(loss, model_distil.trainable_variables)
    optimizer_distil.apply_gradients(zip(gradients, model_distil.trainable_variables))
    metric_distil.update_state(targets, logits)
    return loss, metric_distil.result()

epochs = DEFAULT_EPOCHS
batch_size = DEFAULT_BATCH_SIZE

print("Treinando o DistilBERT...")
for epoch in range(epochs):
    print(f"\nEpoch {epoch + 1}/{epochs}")
    metric_distil.reset_state()
    for i in range(0, len(X_train), batch_size):
        batch_inputs = {k: v[i:i + batch_size] for k, v in X_train_tokens_distil.data.items()}
        batch_targets = y_train.values[i:i + batch_size]
        loss, acc = train_step_distil(batch_inputs, batch_targets)
        if (i // batch_size) % 10 == 0:
            print(f"  Batch {(i // batch_size) + 1}: Loss = {loss:.4f}, Accuracy = {acc:.4f}")

"""#### Avaliação do Resultados para o DistilBERT"""

print("\nAvaliando o DistilBERT no conjunto de teste...")

all_preds = []
for i in range(0, len(X_test), batch_size):
    batch_inputs = {k: v[i:i + batch_size] for k, v in X_test_tokens_distil.data.items()}
    logits = model_distil(batch_inputs).logits
    all_preds.append(logits)

predictions = tf.concat(all_preds, axis=0)
predicted_labels = np.argmax(predictions, axis=1)

y_test_adjusted = y_test.values

accuracy_distil = accuracy_score(y_test_adjusted, predicted_labels)
f1_distil = f1_score(y_test_adjusted, predicted_labels, average='weighted')

print("\nDistilBERT:")
print(f"Accuracy: {accuracy_distil:.4f}")
print(f"F1 Score: {f1_distil:.4f}")
print("\nClassification Report:")
print(classification_report(y_test_adjusted, predicted_labels, target_names=["negativo", "positivo"]))

"""#### Matriz de Confusão para o DistilBERT"""

cm = confusion_matrix(y_test_adjusted, predicted_labels)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["negativo", "positivo"],
            yticklabels=["negativo", "positivo"])
plt.title("Confusion Matrix - DistilBERT (Polarity)")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

print("Saving DistilBERT model to HF Hub...")
save_model_to_hf(
    model=model_distil,
    local_dir="distilbert_model",
    file_name="",
    repo_id="layers2024/distilbert-sentiment",
    is_transformer=True
)
print("DistilBERT model successfully pushed to HF Hub!")

"""## RoBERTa para Classificação

### Resumo

#### 🌐 Classificação de Sentimentos com XLM-RoBERTa

O projeto também utiliza o **XLM-RoBERTa**, uma variante robusta e multilíngue do modelo RoBERTa, com suporte aprimorado para múltiplos idiomas, incluindo o português. Essa abordagem permite avaliar o desempenho de um modelo pré-treinado em escala global para análise de sentimentos em dados nacionais.

---

#### 🔠 Tokenização e Preparação dos Dados
- As avaliações de entrada são tokenizadas com o `XLMRobertaTokenizer`.
- A tokenização inclui padding, truncamento e um limite de tamanho (`max_length`) para padronizar a entrada.
- Os dados são convertidos para tensores compatíveis com o TensorFlow.

---

#### ⚖️ Balanceamento de Classes
O modelo aplica **pesos de classe dinâmicos** calculados com base na distribuição de sentimentos positivos e negativos no dataset. Isso assegura que o modelo não favoreça a classe majoritária durante o treinamento.

---

#### 💻 Configuração de GPU
Antes do treinamento, o projeto ativa o crescimento de memória nas GPUs disponíveis (se houver) para evitar alocação total e permitir uso mais eficiente do hardware.

---

#### 🧠 Treinamento do Modelo
O modelo `TFXLMRobertaForSequenceClassification` é treinado com:
- Otimizador **AdamWeightDecay**
- Função de perda customizada com pesos de classe
- Acompanhamento da acurácia com `SparseCategoricalAccuracy`
- Loop de treinamento manual utilizando `GradientTape` para controle total

O treinamento ocorre em batches definidos pelo parâmetro global `DEFAULT_BATCH_SIZE`, por um número de épocas determinado.

---

#### 🧪 Avaliação do Modelo
Após o treinamento, o modelo XLM-RoBERTa é avaliado com os dados de teste:
- **Acurácia**
- **F1 Score (ponderado)**
- **Relatório de classificação** com métricas detalhadas para cada classe
- **Matriz de confusão** visual, destacando os acertos e erros de classificação por polaridade

---

#### ☁️ Publicação no Hugging Face Hub
O modelo treinado é exportado e publicado automaticamente no **Hugging Face Hub**, utilizando Git LFS para suporte a arquivos grandes. Isso garante que o modelo possa ser reutilizado e compartilhado com a comunidade de forma simples e eficaz.

---

Essa etapa demonstra a capacidade de modelos multilíngues de capturar nuances linguísticas em português, oferecendo uma solução escalável e eficiente para análise de sentimentos em ambientes multiculturais.

### Código
"""

counts = np.array([
    df[df["polarity"] == 0].shape[0],  # negativo
    df[df["polarity"] == 1].shape[0]   # positivo
])
total = counts.sum()

class_weights = {i: total / count for i, count in enumerate(counts)}
print("Class weights:", class_weights)

gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError as e:
        print(e)

# Tokenizer and model (binary classification)
tokenizer_xlm = XLMRobertaTokenizer.from_pretrained("xlm-roberta-base")
model_roberta = TFXLMRobertaForSequenceClassification.from_pretrained("xlm-roberta-base", num_labels=2)

# X_train_tokens_roberta = tokenizer_xlm(list(X_train), padding=True, truncation=True, return_tensors="tf")
X_train_tokens_roberta = tokenizer_xlm(list(X_train), padding='max_length', truncation=True, max_length=128, return_tensors="tf")
X_test_tokens_roberta = tokenizer_xlm(list(X_test), padding=True, truncation=True, return_tensors="tf")

optimizer_roberta = AdamWeightDecay(learning_rate=3e-5)
metric_roberta = tf.keras.metrics.SparseCategoricalAccuracy()

counts = np.array([
    df[df["polarity"] == 0].shape[0],
    df[df["polarity"] == 1].shape[0]
])
total = counts.sum()
class_weights = {i: total / count for i, count in enumerate(counts)}
weights_tensor = tf.constant([class_weights[0], class_weights[1]], dtype=tf.float32)

def weighted_loss_roberta(y_true, y_pred):
    losses = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)
    sample_weights = tf.gather(weights_tensor, tf.cast(y_true, tf.int32))
    return tf.reduce_mean(losses * sample_weights)

@tf.function
def train_step_roberta(inputs, targets):
    with tf.GradientTape() as tape:
        outputs = model_roberta(inputs)
        logits = outputs.logits
        loss = weighted_loss_roberta(targets, logits)
    gradients = tape.gradient(loss, model_roberta.trainable_variables)
    optimizer_roberta.apply_gradients(zip(gradients, model_roberta.trainable_variables))
    metric_roberta.update_state(targets, logits)
    return loss, metric_roberta.result()

epochs = DEFAULT_EPOCHS
batch_size = DEFAULT_BATCH_SIZE #8

print("Treinando o RoBERTa...")
for epoch in range(epochs):
    print(f"\nEpoch {epoch+1}/{epochs}")
    metric_roberta.reset_state()
    for i in range(0, len(X_train), batch_size):
        batch_inputs = {k: v[i:i+batch_size] for k, v in X_train_tokens_roberta.data.items()}
        batch_targets = y_train.values[i:i+batch_size]
        loss, acc = train_step_roberta(batch_inputs, batch_targets)
        if (i // batch_size) % 10 == 0:
            print(f"  Batch {(i // batch_size)+1}: Loss = {loss:.4f}, Accuracy = {acc:.4f}")

"""#### Avaliação de Resultados para o RoBERTa"""

print("\nAvaliando o RoBERTa no conjunto de teste...")

all_preds = []
for i in range(0, len(X_test), batch_size):
    batch_inputs = {k: v[i:i+batch_size] for k, v in X_test_tokens_roberta.data.items()}
    logits = model_roberta(batch_inputs).logits
    all_preds.append(logits)

predictions_roberta = tf.concat(all_preds, axis=0)
predicted_labels_roberta = np.argmax(predictions_roberta, axis=1)

y_test_adjusted = y_test.values

accuracy_roberta = accuracy_score(y_test_adjusted, predicted_labels_roberta)
f1_roberta = f1_score(y_test_adjusted, predicted_labels_roberta, average='weighted')

print("\nRoBERTa:")
print(f"Accuracy: {accuracy_roberta:.4f}")
print(f"F1 Score: {f1_roberta:.4f}")
print("\nClassification Report:")
print(classification_report(y_test_adjusted, predicted_labels_roberta, target_names=["negativo", "positivo"]))

"""#### Matriz de Confusão para o RoBERTa"""

cm = confusion_matrix(y_test_adjusted, predicted_labels_roberta)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["negativo", "positivo"],
            yticklabels=["negativo", "positivo"])
plt.title("Confusion Matrix - RoBERTa (Polarity)")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

print("Saving RoBERTa model to HF Hub...")
save_model_to_hf(
    model=model_roberta,
    local_dir="roberta_model",
    file_name="",
    repo_id="layers2024/roberta-sentiment",
    is_transformer=True
)
print("RoBERTa model successfully pushed to HF Hub!")

"""## SVM + Sentence-BERT para Classificação

### Resumo

#### 🧠 Classificação com Sentence-BERT + SVM

Além dos modelos Transformers fine-tunados, o projeto também utiliza uma abordagem híbrida mais leve combinando **Sentence-BERT** para extração de embeddings semânticos com um **classificador SVM** tradicional.

---

#### 🧩 Geração de Embeddings com Sentence-BERT
O modelo `distiluse-base-multilingual-cased-v1`, da biblioteca **Sentence-Transformers**, é utilizado para transformar os textos das avaliações em vetores numéricos que capturam o significado semântico de cada comentário.

- Os embeddings são gerados para os conjuntos de treino e teste.
- Essa etapa é eficiente e dispensa o fine-tuning completo de um modelo Transformer.

---

#### 🧪 Classificação com SVM
Com os embeddings gerados, é treinado um modelo **Support Vector Machine (SVM)** utilizando o Scikit-learn:

- O classificador é configurado com `class_weight="balanced"` para compensar possíveis desbalanceamentos no dataset.
- Após o treinamento, o modelo é testado com os embeddings do conjunto de teste.

---

#### 📊 Avaliação do Modelo
A performance do SVM é avaliada com base em:
- **Relatório de classificação completo** com precisão, recall e F1 score por classe
- **Acurácia geral**
- **F1 Score ponderado**
- **Matriz de confusão** para visualizar os acertos e erros na polaridade prevista

---

#### ☁️ Publicação no Hugging Face Hub
O modelo SVM treinado é serializado com `joblib` e publicado no **Hugging Face Hub** através da função `save_sklearn_model_to_hf()`.

Essa abordagem oferece uma alternativa eficiente e leve aos modelos Transformers completos, ideal para aplicações com restrições de recursos computacionais.

---

O uso de Sentence-BERT com SVM demonstra a eficácia de modelos baseados em embeddings prontos para tarefas de classificação binária, com excelente equilíbrio entre desempenho e eficiência.

### Código
"""

svm_sbert = SVC(class_weight="balanced")

y_train_sbert = y_train.values
y_test_sbert = y_test.values

model_sbert = SentenceTransformer("distiluse-base-multilingual-cased-v1")
print("Modelo Sentence-BERT carregado com sucesso.")

print("Gerando embeddings para os dados de treino...")
X_train_sbert = model_sbert.encode(X_train.tolist(), show_progress_bar=True)

print("Gerando embeddings para os dados de teste...")
X_test_sbert = model_sbert.encode(X_test.tolist(), show_progress_bar=True)

svm_sbert = SVC(class_weight="balanced")
svm_sbert.fit(X_train_sbert, y_train_sbert)

y_pred_sbert = svm_sbert.predict(X_test_sbert)

"""#### Avaliação de Resultados para o SVM + Sentence-BERT"""

print("\nRelatório de Classificação para Sentence-BERT + SVM:")
print(classification_report(y_test_sbert, y_pred_sbert, target_names=["negativo", "positivo"]))

accuracy_sbert = accuracy_score(y_test_sbert, y_pred_sbert)
f1_sbert = f1_score(y_test_sbert, y_pred_sbert, average='weighted')

print(f"Accuracy: {accuracy_sbert:.4f}")
print(f"F1 Score: {f1_sbert:.4f}")

"""#### Matriz de Confusão para o SVM + Sentence-BERT"""

cm = confusion_matrix(y_test_sbert, y_pred_sbert)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["negativo", "positivo"],
            yticklabels=["negativo", "positivo"])
plt.title("Confusion Matrix - Sentence-BERT + SVM (Polarity)")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

save_sklearn_model_to_hf(
    model=svm_sbert,
    file_path="svm_sentencebert_model.joblib",
    repo_id="layers2024/svm-sentencebert-sentiment"
)

"""## SVM + Universal Sentence Encoder (USE) para Classificação

### Resumo

#### 🔡 Classificação com Universal Sentence Encoder (USE) + SVM

O projeto também explora o uso do **Universal Sentence Encoder Multilíngue (USE)** em conjunto com um classificador **SVM**, oferecendo uma solução leve, eficiente e sem necessidade de fine-tuning para a tarefa de classificação de sentimentos.

---

#### 🌐 Geração de Embeddings com USE
O modelo `universal-sentence-encoder-multilingual/3`, hospedado no **TensorFlow Hub**, é utilizado para transformar as avaliações textuais em vetores numéricos de alta qualidade semântica.

- Os embeddings são gerados para os conjuntos de treino e teste.
- O processo é simples, rápido e compatível com múltiplos idiomas.

---

#### ⚖️ Padronização dos Embeddings
Antes do treinamento, os vetores gerados são padronizados com `StandardScaler` para garantir melhor desempenho do classificador SVM.

---

#### 🧪 Classificação com SVM
Um **Support Vector Machine (SVM)** com `class_weight="balanced"` é treinado com os embeddings do USE para prever a polaridade das avaliações.

Essa abordagem tradicional oferece bons resultados com baixo custo computacional, ideal para cenários com restrições de recursos.

---

#### 📊 Avaliação do Modelo
O desempenho da combinação **USE + SVM** é avaliado por meio de:

- **Acurácia geral**
- **F1 Score ponderado**
- **Relatório de classificação** com métricas por classe
- **Matriz de confusão** com visualização das previsões corretas e incorretas

---

#### ☁️ Publicação no Hugging Face Hub
Após o treinamento, o modelo SVM é salvo e publicado no **Hugging Face Hub** com o nome `svm-use-sentiment`, permitindo reutilização futura e compartilhamento com a comunidade.

---

O uso do **USE + SVM** mostra como é possível obter **bons resultados com soluções leves**, sem a necessidade de treinar modelos grandes ou ajustar hiperparâmetros complexos, o que torna essa abordagem uma excelente alternativa prática e acessível.

### Código
"""

use_model_url = "https://tfhub.dev/google/universal-sentence-encoder-multilingual/3"
use_model = hub.load(use_model_url)
print("Universal Sentence Encoder loaded.")

def get_use_embeddings(texts):
    embeddings = use_model(texts)
    return embeddings.numpy()

print("Gerando embeddings para os dados de treino...")
X_train_use = get_use_embeddings(X_train.tolist())
print("Gerando embeddings para os dados de teste...")
X_test_use = get_use_embeddings(X_test.tolist())

scaler = StandardScaler()
X_train_use = scaler.fit_transform(X_train_use)
X_test_use = scaler.transform(X_test_use)

y_train_use = y_train.values
y_test_use = y_test.values

svm_use = SVC(class_weight="balanced")
svm_use.fit(X_train_use, y_train_use)
y_pred_use = svm_use.predict(X_test_use)

"""#### Avaliação de Resultados para o SVM + Universal Sentence Encoder (USE)"""

print("\nRelatório de Classificação para USE + SVM:")
print(classification_report(y_test, y_pred_use, target_names=["negativo", "positivo"]))

accuracy_use = accuracy_score(y_test, y_pred_use)
f1_use = f1_score(y_test, y_pred_use, average='weighted')

print(f"Accuracy: {accuracy_use:.4f}")
print(f"F1 Score: {f1_use:.4f}")

"""#### Matriz de Confusão para o SVM + Universal Sentence Encoder (USE)"""

# Convert numeric polarity values to string labels for visualization
label_map = {0: "negativo", 1: "positivo"}
y_test_str = [label_map[r] for r in y_test]
y_pred_use_str = [label_map[r] for r in y_pred_use]

# Generate and plot the binary confusion matrix
cm = confusion_matrix(y_test_str, y_pred_use_str, labels=["negativo", "positivo"])
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["negativo", "positivo"],
            yticklabels=["negativo", "positivo"])
plt.title("Confusion Matrix - USE + SVM (Polarity)")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

save_sklearn_model_to_hf(
    model=svm_use,
    file_path="svm_use_model.joblib",
    repo_id="layers2024/svm-use-sentiment"
)

"""# Comparativo de Métricas e Resultados

### Resumo

#### 📈 Comparação de Desempenho dos Modelos

Ao final do experimento, os principais modelos utilizados no projeto são comparados com base em suas métricas de desempenho — **Acurácia** e **F1-Score**. Essa análise permite identificar quais abordagens foram mais eficazes na tarefa de classificação de sentimentos.

---

#### 🧪 Modelos Avaliados

Os seguintes modelos foram comparados:

- **BERT** (Português - fine-tuned)
- **DistilBERT** (Multilíngue - fine-tuned)
- **XLM-RoBERTa** (Multilíngue - fine-tuned)
- **SVM + Sentence-BERT** (embeddings semânticos + classificador leve)
- **SVM + USE** (Universal Sentence Encoder + SVM)

---

#### 📊 Métricas Utilizadas

- **Acurácia**: proporção total de classificações corretas.
- **F1-Score ponderado**: equilíbrio entre precisão e recall, levando em conta o desbalanceamento entre classes.

---

#### 📉 Visualização dos Resultados

Os resultados são apresentados em um **gráfico de barras**, comparando lado a lado as pontuações de acurácia e F1-Score para cada modelo.

Essa visualização facilita a interpretação das performances relativas e ajuda na escolha do modelo mais adequado conforme os critérios de eficiência, precisão e custo computacional.

---

Essa análise consolidada reforça a importância de testar múltiplas abordagens, combinando modelos de última geração com soluções mais leves, para encontrar o melhor equilíbrio entre **desempenho e eficiência** em projetos reais de PLN.

### Código
"""

# Cria um dicionário com os resultados
resultados = {
    "Modelo": ["BERT", "DistilBERT", "RoBERTa", "SVM + Sentence-BERT", "SVM + USE"],
    "Acurácia": [accuracy_bert, accuracy_distil, accuracy_roberta, accuracy_sbert, accuracy_use],
    "F1-Score": [f1_bert, f1_distil, f1_roberta, f1_sbert, f1_use]
}

# Cria um DataFrame pandas com os resultados
df_resultados = pd.DataFrame(resultados)

# Exibe o DataFrame
print(df_resultados)

"""#### Gráfico com Comparação de Desempenho dos Modelos"""

plt.figure(figsize=(14, 6))
# Turn off the automatic legend by passing legend=False
df_resultados.plot(x="Modelo", y=["Acurácia", "F1-Score"], kind="bar",
                   width=0.6, color=["skyblue", "lightcoral"], legend=False)

plt.title("Comparação de Desempenho dos Modelos")
plt.ylabel("Pontuação")
plt.xticks(rotation=45, ha="right")

# Manually add the legend outside the plot (to the right)
plt.legend(["Acurácia", "F1-Score"], title="Métrica",
           bbox_to_anchor=(1.05, 1), loc="upper left")

plt.tight_layout()
plt.show()

"""# Classificação com In-Context Learning

### Resumo

#### 🤖 Classificação com Modelos de Linguagem Generativa (LLMs)

Nesta etapa, o projeto avalia a capacidade de modelos generativos de linguagem (LLMs) — **OpenAI GPT-4** e **Google Gemini 1.5** — em classificar avaliações de produtos como **"positivo"** ou **"negativo"**, sem qualquer ajuste fino (zero-shot).

---

#### 🧾 Prompt de Instrução
Ambos os modelos recebem o mesmo prompt estruturado que simula um cenário de assistente virtual de análise de sentimentos. O prompt é projetado para solicitar uma resposta clara e objetiva, sem explicações adicionais.

---

#### 🧪 Execução da Classificação
- 10 avaliações aleatórias são selecionadas para teste com cada modelo.
- A resposta de cada modelo é comparada com o sentimento real rotulado (`positivo` ou `negativo`).
- Emojis e indicadores visuais são adicionados à classificação para facilitar a leitura dos resultados.

---

#### ✅ Avaliação de Desempenho

As métricas calculadas para cada modelo incluem:
- **Acurácia global** (% de classificações corretas)
- **Total de acertos e erros**
- **Acurácia por categoria** (positivo / negativo)
- **Relatório de classificação (precision, recall, F1-Score)**
- **Matriz de confusão**

Essas métricas oferecem uma visão detalhada sobre a performance dos modelos tanto no geral quanto por classe.

---

#### 📊 Visualizações
São gerados diversos gráficos comparativos:
- **Gráfico de barras** com a acurácia geral de cada modelo
- **Gráfico por categoria**, exibindo a acurácia específica para sentimentos positivos e negativos
- **Matrizes de confusão** lado a lado para OpenAI GPT-4 e Google Gemini 1.5

Essas visualizações ajudam a entender não apenas quem acerta mais, mas **onde** cada modelo tem maior ou menor dificuldade.

---

Essa etapa demonstra a flexibilidade e poder dos LLMs modernos, permitindo resolver tarefas de PLN com precisão competitiva e **sem necessidade de treinar modelos complexos**, tornando-os ideais para prototipagem rápida e soluções de baixo custo operacional.

### Código

#### Declaração do Prompt e Funções Úteis
"""

# Define o temeplate do prompt
prompt_template = """
Você é um assistente de análise de sentimentos. Sua tarefa é classificar avaliações de produtos como "positivo" ou "negativo".

Aqui está uma avaliação de um produto:
{review_text}

Classifique a avaliação acima como "Positivo" ou "Negativo". Responda apenas com a classificação, sem adicionar comentários ou explicações adicionais.
"""

# Define função para exibição da classificação
def add_emoji_to_classification(classification):
  if classification == "Positivo":
    return "😊 " + classification
  elif classification == "Negativo":
    return "😞 " + classification
  else:
    return classification

# Define função para comparação com resultado da coluna "sentiment"
def compare_classification_with_actual(classification, actual_sentiment):
  is_correct = classification.lower() == actual_sentiment.lower()
  result = "✅ Correto" if is_correct else "❌ Incorreto"
  return result, is_correct

"""#### In-Context Learning com OpenAI (GPT-4o)"""

llm = ChatOpenAI(
    model_name="gpt-4o",
    temperature=0
)

def classify_with_openai(review_text):
    prompt = prompt_template.format(review_text=review_text)

    response = llm.predict(prompt)
    return response.strip()

random_reviews = df.sample(n=10)
openai_results = []

print("Classificação da OpenAI GPT-4")
print("=" * 90)

for index, row in random_reviews.iterrows():
    review_text = row['review']
    classification = classify_with_openai(review_text)
    display_classification = add_emoji_to_classification(classification)
    result, is_correct = compare_classification_with_actual(classification, row['sentiment'])

    openai_results.append({
        'Review': review_text,
        'Sentiment': row['sentiment'],
        'Classification': classification,
        'Display Classification': display_classification,
        'Result': result,
        'Is Correct': is_correct
    })

    print(f"\nAvaliação: {review_text}")
    print(f"Classificação da OpenAI: {display_classification}")
    print("-" * 90)
    print(f"Sentimento Real: {row['sentiment'].capitalize()}")
    print(f"Resultado: {result}")

"""#### In-Context Learning com Google Gemini 1.5"""

genai.configure(api_key=myKey)

# Espcifica o modelo do Gemini
model = genai.GenerativeModel("gemini-1.5-flash-latest")

def classify_with_gemini(review_text):
    response = model.generate_content(prompt_template.format(review_text=review_text))
    classification = response.text.strip()
    return classification

# Classifica 10 reviews aleatórias
random_reviews = df.sample(n=10)
gemini_results = []  # Armazena os resultados do Gemini

print("Classificação do Google Gemini 1.5")
print("=" * 90)

for index, row in random_reviews.iterrows():
    review_text = row['review']
    classification = classify_with_gemini(review_text)
    display_classification = add_emoji_to_classification(classification)
    result, is_correct = compare_classification_with_actual(classification, row['sentiment'])

    gemini_results.append({
        'Review': review_text,
        'Sentiment': row['sentiment'],
        'Classification': classification,
        'Display Classification': display_classification,
        'Result': result,
        'Is Correct': is_correct
    })

    print(f"\nAvaliação: {review_text}")
    print(f"Classificação do Gemini: {display_classification}")
    print("-" * 90)
    print(f"Sentimento Real: {row['sentiment'].capitalize()}")
    print(f"Resultado: {result}")

"""#### Comparativo de Métricas e Resultdos

##### Análise Consolidada
"""

df_openai = pd.DataFrame(openai_results)
df_gemini = pd.DataFrame(gemini_results)

accuracy_openai = df_openai['Is Correct'].mean() * 100
accuracy_gemini = df_gemini['Is Correct'].mean() * 100

correct_openai = df_openai['Is Correct'].sum()
wrong_openai = len(df_openai) - correct_openai

correct_gemini = df_gemini['Is Correct'].sum()
wrong_gemini = len(df_gemini) - correct_gemini

accuracy_summary = pd.DataFrame({
    'LLM': ['OpenAI GPT-4', 'Google Gemini 1.5'],
    'Accuracy (%)': [accuracy_openai, accuracy_gemini],
    'Correct Predictions': [correct_openai, correct_gemini],
    'Incorrect Predictions': [wrong_openai, wrong_gemini]
})

print("\nOverall Accuracy Summary:")
print(accuracy_summary)

"""##### Gŕafico de Comparação"""

plt.figure(figsize=(8, 6))

colors = ['#3498db', '#e74c3c']

bars = plt.bar(
    accuracy_summary['LLM'],
    accuracy_summary['Accuracy (%)'],
    color=colors
)

for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height + 1,
        f'{height:.1f}%',
        ha='center',
        va='bottom',
        fontsize=12,
        color='black'
    )

# Set y-limit and labels
plt.ylim(0, 100)
plt.ylabel('Accuracy (%)')
plt.title('LLM Sentiment Classification Accuracy Comparison')
plt.show()

"""##### Resultados Por Categoria"""

categories = ['positivo', 'negativo']

def get_category_performance(df, model_name, categories):
    """
    Returns a DataFrame with columns:
      - Model
      - Category
      - Total
      - Correct
      - Incorrect
      - Accuracy (%)
    for each category in `categories`.
    """
    actuals = df['Sentiment'].str.lower()
    preds = df['Classification'].str.lower()
    data = []

    for cat in categories:
        total = (actuals == cat).sum()
        correct = ((actuals == cat) & (preds == cat)).sum()
        incorrect = total - correct
        accuracy = (correct / total * 100) if total > 0 else 0

        data.append({
            'Model': model_name,
            'Category': cat,
            'Total': total,
            'Correct': correct,
            'Incorrect': incorrect,
            'Accuracy (%)': accuracy
        })

    return pd.DataFrame(data)

df_openai_cat = get_category_performance(df_openai, "OpenAI GPT-4", categories)
df_gemini_cat = get_category_performance(df_gemini, "Google Gemini 1.5", categories)

df_cat = pd.concat([df_openai_cat, df_gemini_cat], ignore_index=True)

print("\nPer-Category Performance Data:")
print(df_cat)

"""##### Gráfico dos Resultados Por Categoria"""

pivot_df = df_cat.pivot(index='Category', columns='Model', values='Accuracy (%)')

plt.figure(figsize=(8, 6))
pivot_df.plot(kind='bar', figsize=(8, 6))

plt.ylim(0, 100)
plt.ylabel('Accuracy (%)')
plt.title('Category-wise Accuracy Comparison')
plt.xticks(rotation=0)
plt.legend(title='Model', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""##### Report com Comparação Detalhada"""

actuals_openai = df_openai['Sentiment'].str.lower()
preds_openai = df_openai['Classification'].str.lower()

actuals_gemini = df_gemini['Sentiment'].str.lower()
preds_gemini = df_gemini['Classification'].str.lower()

print("\nClassification Report for OpenAI GPT-4:")
print(classification_report(actuals_openai, preds_openai, labels=categories, zero_division=0))

print("Classification Report for Google Gemini 1.5:")
print(classification_report(actuals_gemini, preds_gemini, labels=categories, zero_division=0))

"""##### Matriz de Confusão"""

# Create confusion matrices for both models
cm_openai = confusion_matrix(actuals_openai, preds_openai, labels=categories)
cm_gemini = confusion_matrix(actuals_gemini, preds_gemini, labels=categories)

# Create a figure with 1 row and 2 columns, specifying horizontal space
fig, axs = plt.subplots(1, 2, figsize=(12, 5), gridspec_kw={'wspace': 0.5})

# Plot OpenAI GPT-4 confusion matrix on the first subplot
disp_openai = ConfusionMatrixDisplay(confusion_matrix=cm_openai, display_labels=categories)
disp_openai.plot(ax=axs[0], cmap='Blues', values_format='d')
axs[0].set_title('OpenAI GPT-4 Confusion Matrix')

# Plot Google Gemini 1.5 confusion matrix on the second subplot
disp_gemini = ConfusionMatrixDisplay(confusion_matrix=cm_gemini, display_labels=categories)
disp_gemini.plot(ax=axs[1], cmap='Blues', values_format='d')
axs[1].set_title('Google Gemini 1.5 Confusion Matrix')

plt.show()

"""# Conclusão

O projeto **NLP-Sentinel** mostrou que é possível alcançar **alta precisão** na análise de sentimentos em português utilizando tanto modelos supervisionados quanto abordagens modernas com LLMs. A experimentação ampla com diferentes estratégias — desde embeddings e SVM até Transformers e modelos generativos — permitiu identificar o equilíbrio ideal entre **desempenho, custo computacional e simplicidade**.

Além disso, o projeto revelou que abordagens tradicionais como **SVM com Bag of Words/Embeddings** e redes neurais **LSTM/RNN** não se mostraram competitivas neste cenário, sendo descontinuadas devido à sua **baixa eficiência e alto custo**.

A combinação de práticas sólidas de pré-processamento, curadoria de dados e testes controlados contribuiu para resultados robustos e replicáveis. A utilização do **Hugging Face Hub** para versionamento e compartilhamento de modelos também facilitou a organização do projeto.

Este trabalho reforça que, para tarefas de PLN em ambientes reais, a escolha da abordagem ideal depende não apenas de métricas de acurácia, mas também da **viabilidade de aplicação no mundo real** — considerando fatores como escalabilidade, recursos disponíveis e tempo de resposta esperado.

Em resumo, o **NLP-Sentinel** alcançou seu objetivo principal e ofereceu aprendizados valiosos sobre o uso de IA aplicada à linguagem natural no contexto do português brasileiro.
"""